### ISSUE TITLE
feat: support standard route conventions as well as nested routes

### ISSUE THREAD

**Issue by kiliman** [kentcdodds/remix-mdx#3]
MDX routes should behave like normal routes. You should be able to use escape characters. You should also be able to have nested routes.

Currently the mdx route definition doesn't support nested routes. They are always defined as child or *root* route.

**Comment by kiliman** [comment]
I've added support for this, but since it builds on the loader PR, I'll wait until it's merged to submit the new PR.

Basically, I use `defineConventionalRoutes` so it works the same way as it does currently: escape and nested routes, etc.

This returns the current route config. I then just filter the routes for those that end with .mdx, then compile those routes, and patch up the route config with the new filename. Remix then processes the config as usual.

I also added a hash file, so each time the MDX changes, it generates a new hash file. Then on startup I compare the hash with the contents and if it hasn't changed, I skip that file. This way startup is faster if the MDX has already been compiled.

NOTE: You have to ignore everything in the `routes` folder (see config), since Remix processes `app/routes` before calling routes export. Unfortunately it doesn't send the existing route config, so I can't patch it. It simply merges new routes with the defaults. So I need to make sure the default routes is empty, then we call `defineConventionalRoutes` and pass that to `mdxRoutes` so it can compile and patch. You can pass the `ignoredRouteFiles` here, if you have any.

```ts
const ignoredRouteFiles = ['.*', '**/*.css', '**/*.test.{js,jsx,ts,tsx}']
module.exports = {
  cacheDirectory: './node_modules/.cache/remix',
  ignoredRouteFiles: ['**/*'], // ignore everything in routes folder
  routes: async defineRoutes => {
    const conventionalRoutes = defineConventionalRoutes(
      'app',
      ignoredRouteFiles,
    )
    return await mdxRoutes(conventionalRoutes)
  },
}
```
Here's an example of the `.cache` folder. The hash file has to be separate. I originally included the hash in the compiled filename. But this caused the route ids to fail so changes weren't being picked up.

Also, for some reason `<LiveReload/>` isn't being triggered for these changes. I'm not sure if it's because the route files are outside of `/app/routes`. It does build, but you have to manually refresh if you're on the MDX route.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/47168/173618999-7e2e4b30-6503-493b-8c86-9f3a259c66e5.png">

**Comment by kentcdodds** [comment]
Thanks for working on this @kiliman.

I've added a note to the README. We're going to go with a different idea for addressing this that I think will be much better.
